[workspace]
members = [
    "rust/src/game", "rust/src/server",
    "rust/xtask",
]
resolver = "2"

[profile.dev]
lto = "off"

[profile.release]
lto = "fat"
codegen-units = 1

# This allows running `cargo xtask` directly from root
[workspace.dependencies]
# Add shared deps here if needed